### ISSUE TITLE
Import modules from a local conda environment to a Ray worker

### ISSUE THREAD

**Issue by YSHebron** [YSHebron/scl-bioinfo#1]
On PC2P:
Running importing (or running) PC2P_ParallelRay.py causes the following error:
```
(scl) yshebron@LAPTOP-BUICL812:~/scl/scl-bioinfo$ /home/yshebron/miniconda3/envs/scl/bin/python /home/yshebron/scl/scl-bioinfo/PC2P/PC2P_ParallelMultiprocess.py
2023-11-26 19:20:17,339 INFO worker.py:1664 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265 
/home/yshebron/scl/scl-bioinfo
Traceback (most recent call last):
  File "/home/yshebron/scl/scl-bioinfo/PC2P/PC2P_ParallelMultiprocess.py", line 340, in <module>
    Edge_cut_STRING = Find_CNPs_V2(STRING)
                      ^^^^^^^^^^^^^^^^^^^^
  File "/home/yshebron/scl/scl-bioinfo/PC2P/PC2P_ParallelRay.py", line 199, in Find_CNPs_V2
    result_objects_1 = ray.get([CNP.remote(componentOfG,v,mixed_label) for v in nodes])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yshebron/miniconda3/envs/scl/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/yshebron/miniconda3/envs/scl/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/yshebron/miniconda3/envs/scl/lib/python3.11/site-packages/ray/_private/worker.py", line 2563, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::CNP() (pid=31193, ip=172.27.167.250)
RuntimeError: The remote function failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:

ray::CNP() (pid=31193, ip=172.27.167.250)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yshebron/scl/scl-bioinfo/PC2P/PC2P_ParallelRay.py", line 15, in <module>
    ray.init(num_cpus=num_cpus)
           ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Maybe you called ray.init twice by accident? This error can be suppressed by passing in 'ignore_reinit_error=True' or by calling 'ray.shutdown()' prior to 'ray.init()'.
```

Looking at how to make Ray instance use our `environment.yml`.

References:
https://stackoverflow.com/questions/69765007/how-does-ray-handle-package-dependencies
https://discuss.ray.io/t/import-modules-from-a-local-conda-environment-to-a-ray-worker/5000

**Comment by YSHebron** [comment]
FIXED! Added conda_env to PC2P_ParallelRay.py.

**Comment by YSHebron** [comment]
FIXED! Added conda_env to PC2P_ParallelRay.py.
